services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hello_dev
      PGDATA_DEV: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port for debugging if needed

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@db:5432/hello_dev
    env_file:
      - .env.dev
    ports:
      - "4000:4000"
    entrypoint: ["./entrypoint-dev.sh"] #script for check update
    volumes:
      # Mount source code for hot reloading
      - .:/app:cached
      - phoenix_deps:/app/deps    # named volume for dependencies
      - phoenix_build:/app/_build # named voulme for compilation
      - phoenix_node_modules:/app/node_modules
    # Add stdin/tty for interactive debugging
    stdin_open: true
    tty: true

volumes:
  pgdata_dev:
  phoenix_build:
  phoenix_node_modules:
  phoenix_deps:
